// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekagxoekbewojznmzpih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrYWd4b2VrYmV3b2p6bm16cGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTE0MzYsImV4cCI6MjA3MzYyNzQzNn0.lIR1j09xCItSPNh4T5NGoXvT5OHKp0SWjkdqHTsxVpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});